services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase-jaya-jaya
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - metabase-data:/metabase-data
      - ./jaya_jaya_dashboard.db:/app/jaya_jaya_dashboard.db:ro
    networks:
      - metabase-network

volumes:
  metabase-data:
    driver: local

networks:
  metabase-network:
    driver: bridge